import type { InferGetStaticPropsType, NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Flickity from 'react-flickity-component';
import styled from 'styled-components';
import { getCategories } from '../ utils/getCategories';
import { getHeadlines } from '../ utils/getHeadlines';
import Categories from '../components/Categories';

const ImageWrapper = styled.a`
  position: relative;
`;
const DecorativeGradient = styled.div`
  position: absolute;
  top: 0px;
  right: 0px;
  bottom: 0px;
  left: 0px;
  z-index: 3;
  background-image: linear-gradient(to top, #0d0f12, transparent 40%);
`;

const flickityOptions = {
  autoPlay: true,
  prevNextButtons: false,
  cellAlign: 'center',
  groupCells: 1,
};

export const getStaticProps = async () => {
  const headlineMovies = getHeadlines();
  const categories = getCategories();

  return {
    props: {
      headlineMovies,
      categories,
    },
  };
};
const Home: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = ({
  headlineMovies,
  categories,
}) => {
  return (
    <>
      <Head>
        <title>Ana Sayfa - beIN CONNECT</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flickity options={flickityOptions} static={true}>
        {headlineMovies.map((movie) => (
          <Link href={movie.slug} key={movie.id}>
            <ImageWrapper>
              <Image
                key={movie.id}
                src={movie.posterUrl}
                alt={movie.title}
                width={1080}
                height={352.5}
              />
              <DecorativeGradient />
            </ImageWrapper>
          </Link>
        ))}
      </Flickity>

      <Categories categories={categories} />
    </>
  );
};

export default Home;
